const products = [
  {id: '16e11d4d-6358-47bd-b252-438227de8a49', name: 'Standup Desk', description: 'A desk for standing while working, because who you shouldn\'t sit all day long' , imageUrls: ['https://d1zloi9myumgkb.cloudfront.net/images/spn48f-bk-tk-pneumatic-standup-desk.jpg'], price: 199.99, quantity: 100, categories: ['office', 'health']},
  {id: '4ab7f9a4-3d03-445d-b222-e66b6ef0a6cd', name: 'Ergonomic Keyboard', description: 'An ergonomic keyboard that will help prevent wrist and thumb pains.', imageUrls: ['https://www.adesso.com/wp-content/uploads/2018/03/20170315082459.jpg'], price: 79.98, quantity: 100, categories: ['office', 'health']},
  {id: '7c27b055-1187-49d0-aece-93deb97dffe8', name: 'Ergonomic Mouse', description: 'An ergonomic mouse that will help prevent wrist and finger pains.', imageUrls: ['https://www.adesso.com/UploadFiles/20160408022657.jpg'], price: 67.54, quantity: 100, categories: ['office', 'health']},
  {id: 'b6c69306-ed81-488a-8edc-2b57dc07294c', name: 'Advil', description: 'Ibuprofen for the swelling anywhere in your body.', imageUrls: ['https://www.advil.com/sites/default/files/images/products/advil-tablets-new_0_0.png'], price: 3.49, quantity: 200, categories: ['medication']},
  {id: 'caa4bf94-afcb-47c9-9f32-4914c1cc11a2', name: 'Acetaminophen', categories: ['medication'], aveRating:3.44, price:3.49, imageUrls:['https://upload.wikimedia.org/wikipedia/commons/8/8f/Paracetamol-from-xtal-3D-balls.png','https://en.wikipedia.org/wiki/Paracetamol#/media/File:Paracetamol-skeletal.svg'], description:'Paracetamol, also known as acetaminophen and APAP, is a medication used to treat pain and fever. It is typically used for mild to moderate pain relief. There is mixed evidence for its use to relieve fever in children. It is often sold in combination with other medications, such as in many cold medications. Paracetamol is also used for severe pain, such as cancer pain and pain after surgery, in combination with opioid pain medication. It is typically used either by mouth or rectally, but is also available by injection into a vein. Effects last between 2 to 4 hours.\nParacetamol is generally safe at recommended doses. The recommended maximum daily dose for an adult is 3 or 4 grams. Higher doses may lead to toxicity, including liver failure. Serious skin rashes may rarely occur. It appears to be safe during pregnancy and when breastfeeding. In those with liver disease, it may still be used, but in lower doses. It is classified as a mild analgesic. It does not have significant anti-inflammatory activity. How it works is not entirely clear. -Wikipedia', quantity:1},
  {id: 'f3015b76-0c17-42d1-a6a5-496385dc46a8', name: 'Eye drops', categories: ['health', 'medication'], aveRating:4.53, price:5.49, imageUrls:['https://upload.wikimedia.org/wikipedia/commons/6/60/%C3%96gondroppar2.jpg'], description: 'Five pack. Natural tears, dryness relief for your eyes.', quantity: 2},
  {id: 'cb9ed9b6-0819-44eb-a5dd-496385dc46a8', name: 'Noise Cancelling Headphones', categories: ['office', 'productivity'], aveRating:4.2, price:150, imageUrls:['https://ae01.alicdn.com/kf/HTB1BRimazzuK1RjSspeq6ziHVXaU.jpg_q50.jpg'], description: 'Block out distractions while you code.', quantity: 20},
  {id: 'cb9ed9b6-0819-44eb-a5dd-4914c1cc11a2', name: 'Coffee Maker', categories: ['health', 'energy'], aveRating:5, price:32.99, imageUrls:['https://ak7.picdn.net/shutterstock/videos/17523817/thumb/11.jpg'], description: 'Makes incredible coffee', quantity: 25},
  {id: 'f3015b76-0819-44eb-a5dd-4914c1cc11a2', name: 'Pomodoro Timer', categories: ['office', 'productivity'], aveRating:4, price:9.99, imageUrls:['https://images-na.ssl-images-amazon.com/images/I/51ObuwA2MAL._SX425_.jpg'], description: 'Improve your productivity by using the Pomodoro technique.', quantity: 25}
];

module.exports = products;